all: swap pointers factorial

pointers: pointers.c
	gcc -g -Wall -std=c99 -o pointers pointers.c

swap: swap.c
	gcc -g -Wall -std=c99 -o swap swap.c

factorial: factorial.c
	gcc -g -Wall -std=c99 -o factorial factorial.c

clean:
	rm -rf *.o swap pointers factorial